### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useRef')

### ISSUE THREAD

**Issue by sljer** [jp-liu/fit-screen#1]
node v16.17.0
react v16.13.1
![Uploading 1.png…]()
The above error occurs when I try to use this library for a previous project in the lab

**Comment by sljer** [comment]
![Uploading 1.png…]()

**Comment by jp-liu** [comment]
React Hooks was introduced in the React 16.8 release. So using this extension requires react > = 16.9
