### ISSUE TITLE
會有白邊

### ISSUE THREAD

**Issue by kavka002** [jp-liu/fit-screen#2]
用 mode="fit" 會有白邊
 mode="full"   則文字&表格會拉伸

**Comment by jp-liu** [comment]
这个我知道，因为 fit 是保持宽高比，有问题白边是正常的，一般是通过将背后设定相同的色系背景色，来遮挡。
如果需要没有左右白边，请使用 scrollY，这样会保证宽高比的同时让 X 轴撑满，y轴滚动。
去除上下白边，则相反，让x轴滚动，上下撑满
